@echo off
SET BASENAME=accesscontrol
SET SVN_ARCHIVE=C:\Development\SVN\%BASENAME%
SET SVN_BIN=%PROGRAMFILES%\Subversion\bin
SET MAINVERSION=0
SET INCLUDE_FILES=*.php *.txt
SET ZIPCOMMAND=%PROGRAMFILES%\7-Zip\7z.exe

for /F "TOKENS=1,2*" %%A IN ('%SVN_BIN%\svnlook.exe youngest %SVN_ARCHIVE%') DO SET SUBVERSION=%%A

SET FILENAME=Deploy\%BASENAME%-%MAINVERSION%.%SUBVERSION%.zip
SET ZIPPARAMS=a -tzip %FILENAME% %INCLUDE_FILES%

%ZIPCOMMAND% %ZIPPARAMS%